query: ?filterDurationUpperBorder=300&filterDifficultyUpperBorder=5&filterDurationLowerBorder=300&searchByProblem=false&filterSeasonUpperBorder=2023-2024&filterContestFormat=ICPC&filterDifficultyLowerBorder=4&filterSeasonLowerBorder=2017-2018&order=ID_DESC

friends:
  - ZJU
  - Zhejiang U
  - 浙江大学
  - 浙大

  - Solitary Dream
  - SolitaryDream
  - destination
  - pb0207
  - cxt
  - veckoper
  - Eden_CY

  - nameless story
  - SSerxhs
  - qiqi20021026
  - Randias

not_friends:
  - ZJUT
  - ZJUI
  - 浙江大学城市学院